### ISSUE TITLE
建议在README中写明配置

### ISSUE THREAD

**Issue by DingJunyao** [glazec/hexo-cheatsheets#3]
我在使用中，发现需要将Hexo中原先的`_config.yml`内的`highlight.enable`设为`false`才能正确渲染。

建议在README的 Installation > Enable 中添加这一条。

谢谢！

**Comment by glazec** [comment]
你是对的。谢谢你的建议。你可以开一个pull request吗？

**Comment by DingJunyao** [comment]
> 你是对的。谢谢你的建议。你可以开一个pull request吗？

已开。
